apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: {{ .Values.Service.svcPort }}
      targetPort: {{ .Values.contPort }}